name: BarberFlow Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout del codigo fuente
      uses: actions/checkout@v4

    - name: 2. Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: 3. Instalar Dependencias de Node
      run: npm install

    - name: 4. Compilar Proyecto Angular
      run: npm run build -- --configuration production

    - name: 5. Subir Carpeta de Produccion
      uses: actions/upload-artifact@v4
      with:
        name: barberflow-frontend-dist
        path: dist/
